### ISSUE TITLE
[BUG]  タイピングゲーム　ページ遷移

### ISSUE THREAD

**Issue by subarunrun0812** [ShotaTanemura/ft_transcendence#188]
TypingGame.js. 13
Uncaught TypeError: Cannot set properties of undefined (setting 'onmessage')
    at new TypingGame (TypingGame.js:13:31)
    at Router.changePage (router.js:93:21)
    at Router.goNextPage (router.js:38:17)
    at main.js:134:8

**Comment by subarunrun0812** [comment]
typing game中にsidbarからchatなど他のページに移動する際にエラーになります！
